language: generic

branches:
  only:
    - master
    - develop
    - /^feature\/.*/

stages:
  - name: Build
  - name: Docs
    if: branch = master AND type != pull_request AND NOT fork

jobs:
  include:
    - name: "Linux Ubuntu x86_64"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/env-ubuntu:20.04
        - docker pull rocstreaming/env-ubuntu:18.04
        - docker pull rocstreaming/env-ubuntu:16.04
        - docker pull rocstreaming/env-ubuntu:14.04
      script:
        - scripts/travis/docker.sh rocstreaming/env-ubuntu:20.04 scripts/travis/linux-x86_64/ubuntu-20.04.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu:18.04 scripts/travis/linux-x86_64/ubuntu-18.04.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu:16.04 scripts/travis/linux-x86_64/ubuntu-16.04.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu:14.04 scripts/travis/linux-x86_64/ubuntu-14.04.sh
        - cat build.status

    - name: "Linux x84_64"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/env-debian
        - docker pull rocstreaming/env-fedora
        - docker pull rocstreaming/env-centos
        - docker pull rocstreaming/env-opensuse
        - docker pull rocstreaming/env-archlinux
        - docker pull rocstreaming/env-alpine
      script:
        - scripts/travis/docker.sh rocstreaming/env-debian scripts/travis/linux-x86_64/debian.sh
        - scripts/travis/docker.sh rocstreaming/env-fedora scripts/travis/linux-x86_64/fedora.sh
        - scripts/travis/docker.sh rocstreaming/env-centos scripts/travis/linux-x86_64/centos.sh
        - scripts/travis/docker.sh rocstreaming/env-opensuse scripts/travis/linux-x86_64/opensuse.sh
        - scripts/travis/docker.sh rocstreaming/env-archlinux scripts/travis/linux-x86_64/archlinux.sh
        - scripts/travis/docker.sh rocstreaming/env-alpine scripts/travis/linux-x86_64/alpine.sh
        - cat build.status

    - name: "Linux ARM"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/toolchain-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7
        - docker pull rocstreaming/toolchain-arm-linux-gnueabihf:gcc-4.9
        - docker pull rocstreaming/toolchain-aarch64-linux-gnu:gcc-7.4
      script:
        - scripts/travis/docker.sh rocstreaming/toolchain-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7 scripts/travis/linux-arm/arm-bcm2708hardfp-linux-gnueabi.sh
        - scripts/travis/docker.sh rocstreaming/toolchain-arm-linux-gnueabihf:gcc-4.9 scripts/travis/linux-arm/arm-linux-gnueabihf.sh
        - scripts/travis/docker.sh rocstreaming/toolchain-aarch64-linux-gnu:gcc-7.4 scripts/travis/linux-arm/aarch64-linux-gnu.sh
        - cat build.status

    - name: "Linux build checks"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/env-ubuntu-minimal
        - docker pull rocstreaming/env-ubuntu
      script:
        - scripts/travis/docker.sh rocstreaming/env-ubuntu-minimal scripts/travis/linux-build-checks/optional-features.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu-minimal scripts/travis/linux-build-checks/optional-backends.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu-minimal scripts/travis/linux-build-checks/debug-build.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu scripts/travis/linux-build-checks/check-formatting.sh

    - name: "Linux runtime checks"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/env-ubuntu
      script:
        - scripts/travis/docker.sh rocstreaming/env-ubuntu scripts/travis/linux-runtime-checks/sanitizers-clang.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu scripts/travis/linux-runtime-checks/sanitizers-gcc.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu scripts/travis/linux-runtime-checks/valgrind-debug.sh
        - scripts/travis/docker.sh rocstreaming/env-ubuntu scripts/travis/linux-runtime-checks/valgrind-release.sh

    - name: "Android i686"
      stage: Build
      os: linux
      dist: bionic
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/env-android
      script:
        - scripts/travis/android.sh API=24 NDK_VERSION=21.1.6352462 ABI=i686 scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=28 NDK_VERSION=21.1.6352462 ABI=i686 scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=29 NDK_VERSION=21.1.6352462 ABI=i686 scripts/travis/android/linux-android.sh
        - cat build.status

    - name: "Android x86_64"
      stage: Build
      os: linux
      dist: bionic
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/env-android
      script:
        - scripts/travis/android.sh API=24 NDK_VERSION=21.1.6352462 ABI=x86_64 scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=28 NDK_VERSION=21.1.6352462 ABI=x86_64 scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=29 NDK_VERSION=21.1.6352462 ABI=x86_64 scripts/travis/android/linux-android.sh
        - cat build.status

    - name: "Android ARM"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocstreaming/env-android
      script:
        - scripts/travis/android.sh API=24 NDK_VERSION=21.1.6352462 ABI=aarch64 scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=24 NDK_VERSION=21.1.6352462 ABI=armv7a scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=28 NDK_VERSION=21.1.6352462 ABI=aarch64 scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=28 NDK_VERSION=21.1.6352462 ABI=armv7a scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=29 NDK_VERSION=21.1.6352462 ABI=aarch64 scripts/travis/android/linux-android.sh
        - scripts/travis/android.sh API=29 NDK_VERSION=21.1.6352462 ABI=armv7a scripts/travis/android/linux-android.sh
        - cat build.status

    - name: "macOS Xcode 9.4"
      stage: Build
      os: osx
      osx_image: xcode9.4
      script:
        - scripts/travis/macos/xcode-9.4.sh
      after_failure:
        - cat config.log

    - name: "macOS Xcode 10.2"
      stage: Build
      os: osx
      osx_image: xcode10.2
      script:
        - scripts/travis/macos/xcode-10.2.sh
      after_failure:
        - cat config.log

    - name: "macOS Xcode 11.6"
      stage: Build
      os: osx
      osx_image: xcode11.6
      script:
        - scripts/travis/macos/xcode-11.6.sh
      after_failure:
        - cat config.log

    - name: "roc-streaming.github.io"
      stage: Docs
      script:
        - scripts/travis/trigger.sh roc-streaming%2Froc-streaming.github.io travis
