name: "assign_project"

on:
  issues:
    types:
      - opened

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        id: addItem
        with:
          project-url: "https://github.com/orgs/roc-streaming/projects/5"
          github-token: "${{ secrets.REPO_MANAGEMENT }}"
