name: "assign_project"

on:
  issues:
    types:
      - opened

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        continue-on-error: true
        with:
          repo-token: "${{ secrets.REPO_MANAGEMENT }}"
          project: "kanban board"
          column: "Frontlog"
