name: "pr_closed"

on:
  pull_request_target:
    types:
      - closed

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          remove-labels: 'work in progress,ready for review,review in progress,needs revision,needs rebase'
